### ISSUE TITLE
BigDecimal instead of Float?

### ISSUE THREAD

**Issue by henrik** [ianfleeton/paypal-express#19]
How would you feel about changing from using Float to BigDecimal internally?

We've done this in our fork of paypal-express, though we're now looking at upgrading to your better-maintained fork.

I believe the library avoids float-rounding errors currently by only guaranteeing two-decimal precision, and truncating (not rounding) longer numbers to two decimals. Using BigDecimal instead could be a less fragile way of achieving the same, though maybe it wouldn't be worth to change what isn't broken?

This is what our change looked like, anyway:

* https://github.com/barsoom/paypal-express/commit/b5a7f0af53cb0c92141a028ecc4f11577e52af86
* https://github.com/barsoom/paypal-express/commit/51d74a59141bf58aa56721d0c4b69b37c5730747

**Comment by ianfleeton** [comment]
Hi Henrik,

The truncation doesn't so much avoid errors as hide them to keep PayPal happy. I agree that rounding is better than truncation for PoLS but I'd be tempted to go one further and check that the value given is two decimal places and raise otherwise. This puts the onus on the user to truncate or round. I'm happy to start with your change and go further later and see if there's any upset.

I have no problems with users passing in floats other than in the above case. But let's update wiki and specs to set a better example like you've suggested.

Returning a BigDecimal back out of the API is much more responsible. I can't see this causing any unexpected behaviour changes, can you?

Thanks!

**Comment by henrik** [comment]
I like the idea of having the user do the rounding or truncation!

I agree, returning BigDecimals seems a better way to go. It should be trivial for clients to add on a `.to_f` if anyone really needs that, but the return value should work the same (only without rounding issues) in most contexts.

Thank you!
